### YamlMime:RESTOperationGroup
uid: management.azure.com.frontdoorservice.azurefrontdoorstandardpremium(preview).routes1
name: Routes
apiVersion: 2021-06-01
service: Front Door Service
metadata:
  description: Learn more about [Front Door Service Routes Operations]. How to [Create,Delete,Get,List By Endpoint,Update].
operations:
- uid: management.azure.com.frontdoorservice.azurefrontdoorstandardpremium(preview).routes.create1
  summary: Creates a new route with the specified route name under the specified subscription, resource group, profile, and AzureFrontDoor endpoint.
- uid: management.azure.com.frontdoorservice.azurefrontdoorstandardpremium(preview).routes.delete1
  summary: Deletes an existing route with the specified route name under the specified subscription, resource group, profile, and AzureFrontDoor endpoint.
- uid: management.azure.com.frontdoorservice.azurefrontdoorstandardpremium(preview).routes.get1
  summary: Gets an existing route with the specified route name under the specified subscription, resource group, profile, and AzureFrontDoor endpoint.
- uid: management.azure.com.frontdoorservice.azurefrontdoorstandardpremium(preview).routes.listbyendpoint1
  summary: Lists all of the existing origins within a profile.
- uid: management.azure.com.frontdoorservice.azurefrontdoorstandardpremium(preview).routes.update1
  summary: Updates an existing route with the specified route name under the specified subscription, resource group, profile, and AzureFrontDoor endpoint.
